import Head from 'next/head'
import styles from '../styles/Home.module.scss'
import Layout from '../layout/'
import Hero from '../components/hero'

export default function Home() {
	return (
		<div className={styles.container}>
			<Head>
				<title>Fix My Boat</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<Hero />
			<h1>Content</h1>
		</div>
	)
}

Home.getLayout = function getLayout(Home) {
	return <Layout>{Home}</Layout>
}
