import Head from 'next/head'
import styles from '../styles/Home.module.scss'
import Layout from '../layout'
import Hero from '../components/hero'

import {useContext} from 'react'
import {OrderContext} from '../context/state'
import {useAppContext} from '../context/state'

export default function Home() {
	const [orders, setOrders] = useAppContext()

	const addMore = () => {
		setOrders(prev => [
			...prev,
			{
				title: 'service three',
				price: '$199',
				id: 205,
			},
		])
	}
	console.log(orders)

	return (
		<div className={styles.container}>
			<Head>
				<title>Fix My Boat</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<>
				<Hero />
				<h1>Context</h1>
				<button onClick={addMore}>ADD</button>
				{orders.map(e => (
					<p key={e.id}>{e.title}</p>
				))}
			</>
		</div>
	)
}

Home.getLayout = function getLayout(Home) {
	return <Layout>{Home}</Layout>
}
